### ISSUE TITLE
library does not compile with (at least) Xcode 12.0-12.4

### ISSUE THREAD

**Issue by saurik** [hanickadot/compile-time-regular-expressions#188]
So, I don't know if this is even something you would want to--or even could!--fix, but I noticed that yesterday you committed a change 9496593f8b0cfcfd47af61804d540181d2ff8f6d that would seem to imply you are testing with Xcode. I thereby figured I should at least mention the issue to see what the conclusion might be (and document it for others).

It could very well be that you are simply--as often am I--an old version of Xcode (whether because you know it won't work on newer ones or because you, like me, are usually stuck on 11.3.1 due to refuse no to upgrade to Catalina... I presume that is very-sadly rare, though ;P).

```
./vpn/shared/p2p/ctre/single-header/ctre.hpp:724:29: error: use of class template 'fixed_string' requires template arguments; argument deduction not allowed in template parameter
4477
template <typename Grammar, ctll::fixed_string input, typename ActionSelector = empty_actions, bool IgnoreUnknownActions = false> struct parser { // in c++20
4478
                            ^~~~

```

This seems to be caused by the following LLVM bug, which has already been fixed, but which hasn't been merged into Xcode.

https://bugs.llvm.org/show_bug.cgi?id=47841

As stated, Xcode 11 works, just not Xcode 12. I haven't tested to see if the upcoming Xcode 12.5--which is sadly only supported on macOS 11, which is going to cause massive delays with CI--has this issue fixed (if it doesn't, they sadly went into RC a few days ago, so I could see being forced to wait until Xcode 13).

**Comment by hanickadot** [comment]
Hi, I don't have pre-Catalina macOs available right now. But I will try to help you, can you please let me know values of these defines:

```
__cpp_nontype_template_parameter_class
__cpp_nontype_template_args
__clang_major__
```

It seems for a reason it triggers the c++20 version of API, which surely xcode didn't implement. As in upstream clang released it a few weeks ago.

**Comment by hanickadot** [comment]
Ah, I can see it in CI now I added xcode12.

https://travis-ci.org/github/hanickadot/compile-time-regular-expressions/jobs/768333013

Will try to fix it soon.

**Comment by hanickadot** [comment]
ok, it should be ok, but I will wait for the CI to finish

**Comment by hanickadot** [comment]
❤️ Thank you for reporting it! I wouldn't notice.

**Comment by saurik** [comment]
> Hi, I don't have pre-Catalina macOs available right now.

Oh, I guess I was confusing: Xcode 12 is the latest version of Xcode; if worked fine on Xcode 11 (and so I noted that maybe you--like me--are using old versions of Xcode for some reason).

Regardless: thanks!! (I filed this issue and then immediately went to do other tasks for a while, so I am sorry I wasn't more helpful with the values of the various #defines, but I am even more excited that this is now set up in your CI.)

> It seems for a reason it triggers the c++20 version of API, which surely xcode didn't implement. As in upstream clang released it a few weeks ago.

Ah! I didn't realize that the underlying feature wasn't broken but simply not implemented (and then bypassed by Xcode 11). The issue--as you figured out--is that Apple's clang broke the ability to use __clang_major__ directly by changing the semantics of it to match their Xcode releases instead of "the upstream equivalent clang".
