### ISSUE TITLE
wchar_t based pattern parsing problem

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#34]
The library fails to compile with MSVC 16.0 (Visual Studio 2019 Preview 1).

error C2338: Regular Expression contains syntax error.
find_captures.hpp(11): error C2672: 'find_captures': no matching overloaded function found
etc

**Comment by BenHanson** [comment]
I am unable to reproduce this. Do you have a complete test case I could try?

**Comment by matbech** [comment]
```
#include <compile-time-regular-expressions/include/ctre.hpp>

static constexpr auto Pattern = ctll::basic_fixed_string{ LR"(^(\S+;\d+)\s+(\d+|\d+/\d+)?\s+((\d{1,2})-([A-Z]{3,3})-(\d{4,4})\s+(\d{1,2}):(\d{2,2})(:(\d{2,2})(\.\d{2,2})?)?(\s+\[(\S+),(\S+)\]\s+\(([A-Z]*),([A-Z]*),([A-Z]*),([A-Z]*)\))?)?)" };

int main()
{
	const wchar_t test[]{ L"abc" };
	const wchar_t* begin = test;
	const wchar_t* end = begin + 3;
	const auto results = ctre::re<Pattern>().search(begin, end);
}
```

**Comment by matbech** [comment]
Thank you.
